name: .NET Build

on:
  push:
    branches: [ main, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./BankFlowAnalyzer.sln
      - name: Build
        run: dotnet build ./BankFlowAnalyzer.sln -c Release --no-restore
      - name: Publish App
        run: dotnet publish ./App/App.csproj -c Release -o out --self-contained false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: out/**
